enableChainmailRecipes: true
enableCobbleToGravelStonecutter: true

#Material enum values like OBSIDIAN, BEDROCK
allowed_TUNNELDIGGER_blockList: [STONE, DIORITE, ANDESITE, GRANITE]

customItems:
  enable: true
  enableMruwiKlejnot: true
  enableMruwiKilof: true
  enableMagicznaOrchidea: true
  enableBlogoslawienstwoNieumarlych: true
  enableEnderowyDepozyt: true

blessingsystem:
  drop: 0.1

tunneldigger:
  enable: true

skipsystem:
  enabled: true
  chance: 0.7

chatsystem:
  enabled: true
  range: 200

homesystem:
  enabled: true
  material: DIAMOND
  price: 3

teleportsystem:
  enabled: true
  material: DIAMOND
  price: 5

stackpotion:
  enabled: true
