enableChainmailRecipes: true
enableCobbleToGravelStonecutter: true

#type block values like OBSIDIAN, BEDROCK
allowed_TUNNELDIGGER_blockList: [STONE, COBBLESTONE]

customItems:
  enableMruwiKlejnot: true
  enableMruwiKilof: true
  enableMagicznaOrchidea: true
  enableBlogoslawienstwoNieumarlych: true
  enableEnderowyDepozyt: true

skipsystem:
  enabled: true
  chance: 0.7

chatsystem:
  enabled: true
  range: 200

homesystem:
  enabled: true
  koszt: 3

teleportsystem:
  enabled: true
  koszt: 5

stackpotion:
  enabled: true
  command: p
