enableChainmailRecipes: true
enableCobbleToGravelStonecutter: true

#Material enum values like OBSIDIAN, BEDROCK
allowed_TUNNELDIGGER_blockList: [STONE, COBBLESTONE, DIORITE, ANDESITE, GRANITE]

customItems:
  enable: true
  enableMruwiKlejnot: true
  enableMruwiKilof: true
  enableMagicznaOrchidea: true
  enableBlogoslawienstwoNieumarlych: true
  enableEnderowyDepozyt: true

#USE ONLY FLOATED NUMBERS THERE
#baseDiamondDrop chance fe. 0.5 = 50%
#fortuneDiamondDrop is additional dropchance per fortune lvl added to (100%-baseDiamondDrop)
#for example if baseDiamondDrop = 0.5 and fortuneDiamondDrop = 0.1
#in this example fortune 3 pickaxe there is 80% dropchance of diamond
diamondsystem:
  baseDropChance: 0.7
  fortuneDropChance: 0.1

blessingsystem:
  drop: 0.1

skipsystem:
  enabled: true
  chance: 0.7

chatsystem:
  enabled: true
  range: 200

homesystem:
  enabled: true
  price: 3

teleportsystem:
  enabled: true
  price: 5

stackpotion:
  enabled: true
