name: GitmanikPlugin
version: 2.0.0
main: pl.gitmanik.GitmanikPlugin
api-version: 1.16
commands:

  gtmench:
    permission: gitmanik.admin.enchant
    usage: /gtmench <type> <level>

  gtmdur:
    permission: gitmanik.admin.durability
    usage: /gtmdur <amount>
  gtmlae:
    permission: gitmanik.listentities
    description: List all entities
    usage: /gtmlae <entity type>

  p:
    description: Stack all potions in inventory
    permission: gitmanik.stackpotions
    usage: /p

  gtmvoteskipnight:
    usage: /gtmvoteskipnight
    description: Helper command

  le:
    permission: gitmanik.listenchants
    usage: /le
    description: List all enchants of held item.
