name: GitmanikPlugin
version: 2.0.0
main: pl.gitmanik.GitmanikPlugin
author: Gitmanik
api-version: 1.16
commands:

  gpadmin:
    permission: gitmanik.admin
    usage: /gpadmin [command] [args..]

  p:
    description: Stack all potions in inventory
    permission: gitmanik.stackpotions
    usage: /p

  gtmvoteskipnight:
    usage: /gtmvoteskipnight
    description: Internal Helper command (Skip night feature)

  home:
    usage: /home [name]

  sethome:
    usage: /sethome [name]


